In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("D:\DA - projects\END-TO-END\Hotel-Booking-Demand\data\hotel_bookings.csv")

In [6]:
missing = pd.DataFrame({
    "missing values": df.isnull().sum(),
    "percentage": (df.isnull().sum()/len(df)*100).round(2)
})

missing[missing["missing values"] > 0].sort_values("percentage", ascending = False)

          missing values  percentage
company           112593       94.31
agent              16340       13.69
country              488        0.41
children               4        0.00

In [7]:
df[df["children"].isnull()]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
40600,City Hotel,1,2,2015,August,32,3,1,0,2,...,No Deposit,NaN,NaN,0,Transient-Party,12.0,0,1,Canceled,2015-08-01
40667,City Hotel,1,1,2015,August,32,5,0,2,2,...,No Deposit,14.0,NaN,0,Transient-Party,12.0,0,1,Canceled,2015-08-04
40679,City Hotel,1,1,2015,August,32,5,0,2,3,...,No Deposit,NaN,NaN,0,Transient-Party,18.0,0,2,Canceled,2015-08-04
41160,City Hotel,1,8,2015,August,33,13,2,5,2,...,No Deposit,9.0,NaN,0,Transient-Party,76.5,0,1,Canceled,2015-08-09

In [9]:
df["children"] = df["children"].fillna(0)

In [12]:
df["country"] = df["country"].fillna("Unknown")

In [14]:
df[df["agent"].isnull()].head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,No Deposit,NaN,NaN,0,Transient,107.00,0,0,Check-Out,2015-07-03
18,Resort Hotel,0,0,2015,July,27,1,0,1,2,...,No Deposit,NaN,110.0,0,Transient,107.42,0,0,Check-Out,2015-07-02

In [15]:
df["agent"] = df["agent"].fillna(0)

In [16]:
df[df["company"].isnull()].head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,0.0,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,0.0,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,0.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [17]:
df["company"] = df["company"].fillna(0)

In [18]:
df.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
company                           0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
dtype: int64

In [20]:
df.duplicated().sum()

np.int64(31994)

In [23]:
df[df.duplicated()].head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,0.0,0,Transient,98.00,0,1,Check-Out,2015-07-03
22,Resort Hotel,0,72,2015,July,27,1,2,4,2,...,No Deposit,250.0,0.0,0,Transient,84.67,0,1,Check-Out,2015-07-07
43,Resort Hotel,0,70,2015,July,27,2,2,3,2,...,No Deposit,250.0,0.0,0,Transient,137.00,0,1,Check-Out,2015-07-07
138,Resort Hotel,1,5,2015,July,28,5,1,0,2,...,No Deposit,240.0,0.0,0,Transient,97.00,0,0,Canceled,2015-07-01
200,Resort Hotel,0,0,2015,July,28,7,0,1,1,...,No Deposit,240.0,0.0,0,Transient,109.80,0,3,Check-Out,2015-07-08

In [24]:
df = df.drop_duplicates()

In [26]:
df.duplicated().sum()

np.int64(0)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87396 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           87396 non-null  object
 1   is_canceled                     87396 non-null  int64
 2   lead_time                       87396 non-null  int64
 3   arrival_date_year               87396 non-null  int64
 4   arrival_date_month              87396 non-null  object
 5   arrival_date_week_number        87396 non-null  int64
 6   arrival_date_day_of_month       87396 non-null  int64
 7   stays_in_weekend_nights         87396 non-null  int64
 8   stays_in_week_nights            87396 non-null  int64
 9   adults                          87396 non-null  int64
 10  children                        87396 non-null  float64
 11  babies                          87396 non-null  int64
 12  meal                            87396 non-null  object
 13  country                         87396 non-null  object
 14  market_segment                  87396 non-null  object
 15  distribution_channel            87396 non-null  object
 16  is_repeated_guest               87396 non-null  int64
 17  previous_cancellations          87396 non-null  int64
 18  previous_bookings_not_canceled  87396 non-null  int64
 19  reserved_room_type              87396 non-null  object
 20  assigned_room_type              87396 non-null  object
 21  booking_changes                 87396 non-null  int64
 22  deposit_type                    87396 non-null  object
 23  agent                           87396 non-null  float64
 24  company                         87396 non-null  float64
 25  days_in_waiting_list            87396 non-null  int64
 26  customer_type                   87396 non-null  object
 27  adr                             87396 non-null  float64
 28  required_car_parking_spaces     87396 non-null  int64
 29  total_of_special_requests       87396 non-null  int64
 30  reservation_status              87396 non-null  object
 31  reservation_status_date         87396 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 22.0+ MB

In [28]:
df["childern"] = df["children"].astype(int)
df["agent"] = df["agent"].astype(int)
df["company"] = df["company"].astype(int)

In [29]:
df[df["adults"] == 0]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,childern
2224,Resort Hotel,0,1,2015,October,41,6,0,3,0,...,0,174,0,Transient-Party,0.00,0,0,Check-Out,2015-10-06,0
2409,Resort Hotel,0,0,2015,October,42,12,0,0,0,...,0,174,0,Transient,0.00,0,0,Check-Out,2015-10-12,0
3181,Resort Hotel,0,36,2015,November,47,20,1,2,0,...,38,0,0,Transient-Party,0.00,0,0,Check-Out,2015-11-23,0
3684,Resort Hotel,0,165,2015,December,53,30,1,4,0,...,308,0,122,Transient-Party,0.00,0,0,Check-Out,2016-01-04,0
3708,Resort Hotel,0,165,2015,December,53,30,2,4,0,...,308,0,122,Transient-Party,0.00,0,0,Check-Out,2016-01-05,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117204,City Hotel,0,296,2017,July,30,27,1,3,0,...,9,0,0,Transient,98.85,0,1,Check-Out,2017-07-31,2
117274,City Hotel,0,276,2017,July,31,30,2,1,0,...,9,0,0,Transient,93.64,0,2,Check-Out,2017-08-02,2
117303,City Hotel,0,291,2017,July,30,29,2,2,0,...,9,0,0,Transient,98.85,0,1,Check-Out,2017-08-02,2
117453,City Hotel,0,159,2017,July,31,31,1,3,0,...,9,0,0,Transient,121.88,0,1,Check-Out,2017-08-04,2
118200,City Hotel,0,10,2017,August,32,12,2,2,0,...,0,0,0,Transient-Party,6.00,0,1,Check-Out,2017-08-16,3

In [31]:
df.loc[df["adults"] == 0,
    ["adults","children","babies","hotel","is_canceled"]]

        adults  children  babies         hotel  is_canceled
2224         0       0.0       0  Resort Hotel            0
2409         0       0.0       0  Resort Hotel            0
3181         0       0.0       0  Resort Hotel            0
3684         0       0.0       0  Resort Hotel            0
3708         0       0.0       0  Resort Hotel            0
...        ...       ...     ...           ...          ...
117204       0       2.0       0    City Hotel            0
117274       0       2.0       0    City Hotel            0
117303       0       2.0       0    City Hotel            0
117453       0       2.0       0    City Hotel            0
118200       0       3.0       0    City Hotel            0

[385 rows x 5 columns]

In [32]:
df = df[df["adults"] > 0]

In [34]:
df[df["adults"] == 0].shape

(0, 33)

In [35]:
df[df["adr"] < 0]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,childern
14969,Resort Hotel,0,195,2017,March,10,5,4,6,2,...,273,0,0,Transient-Party,-6.38,0,0,Check-Out,2017-03-15,0

In [36]:
df = df[df["adr"] >= 0]

In [40]:
df[df["adr"] > 1000][["adr", "hotel", "adults", "children", "babies", "stays_in_weekend_nights", "stays_in_week_nights", 
      "reserved_room_type", "assigned_room_type", "deposit_type", "is_canceled"]]

,adr,hotel,adults,children,babies,stays_in_weekend_nights,stays_in_week_nights,reserved_room_type,assigned_room_type,deposit_type,is_canceled
48515,5400.0,City Hotel,2,0.0,0,0,1,A,A,Non Refund,1

In [41]:
df["adr"].describe()

count    87010.000000
mean       106.583747
std         54.913712
min          0.000000
25%         72.250000
50%         98.330000
75%        134.100000
max       5400.000000
Name: adr, dtype: float64

In [42]:
df["adr"].sort_values(ascending=False).head()

48515     5400.0
111403     510.0
15083      508.0
103912     451.5
13142      450.0
Name: adr, dtype: float64

In [43]:
df[df["adr"] < 1000]["adr"].describe()

count    87009.000000
mean       106.522910
std         51.898983
min          0.000000
25%         72.250000
50%         98.330000
75%        134.100000
max        510.000000
Name: adr, dtype: float64

In [45]:
df[df["adr"] == 5400].T

                                        48515
hotel                              City Hotel
is_canceled                                 1
lead_time                                  35
arrival_date_year                        2016
arrival_date_month                      March
arrival_date_week_number                   13
arrival_date_day_of_month                  25
stays_in_weekend_nights                     0
stays_in_week_nights                        1
adults                                      2
children                                  0.0
babies                                      0
meal                                       BB
country                                   PRT
market_segment                  Offline TA/TO
distribution_channel                    TA/TO
is_repeated_guest                           0
previous_cancellations                      0
previous_bookings_not_canceled              0
reserved_room_type                          A
assigned_room_type                          A
booking_changes                             1
deposit_type                       Non Refund
agent                                      12
company                                     0
days_in_waiting_list                        0
customer_type                       Transient
adr                                    5400.0
required_car_parking_spaces                 0
total_of_special_requests                   0
reservation_status                   Canceled
reservation_status_date            2016-02-19
childern                                    0

In [46]:
df = df[df["adr"] != 5400]

In [47]:
df[df["adr"] > 1000].shape

(0, 33)

In [48]:
df["lead_time"].describe()

count    87009.000000
mean        79.861566
std         86.007673
min          0.000000
25%         11.000000
50%         49.000000
75%        125.000000
max        737.000000
Name: lead_time, dtype: float64

In [50]:
df[df["lead_time"] > 365]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,childern
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,0,0,0,Transient,0.00,0,0,Check-Out,2015-07-01,0
81,Resort Hotel,1,368,2015,July,27,3,3,7,2,...,40,0,0,Contract,55.68,0,0,Canceled,2015-05-19,0
225,Resort Hotel,0,394,2015,July,28,8,2,5,2,...,40,0,0,Contract,89.68,0,0,Check-Out,2015-07-15,0
245,Resort Hotel,0,366,2015,July,28,9,2,5,2,...,40,0,0,Contract,134.73,0,0,Check-Out,2015-07-16,0
890,Resort Hotel,0,460,2015,August,32,3,2,5,1,...,40,0,0,Contract,77.54,0,0,Check-Out,2015-08-10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118952,City Hotel,0,457,2017,August,34,25,0,2,2,...,6,0,0,Transient-Party,122.40,0,1,Check-Out,2017-08-27,0
119053,City Hotel,0,518,2017,August,34,26,2,1,2,...,229,0,0,Transient-Party,112.67,0,1,Check-Out,2017-08-29,0
119057,City Hotel,0,518,2017,August,34,26,2,1,2,...,229,0,0,Transient-Party,112.67,0,1,Check-Out,2017-08-29,0
119102,City Hotel,0,518,2017,August,34,26,2,1,1,...,229,0,0,Transient-Party,0.00,0,0,Check-Out,2017-08-29,0
119148,City Hotel,0,457,2017,August,34,25,2,3,2,...,6,0,0,Transient-Party,122.40,0,1,Check-Out,2017-08-30,0

In [52]:
df[df["adults"] > 10].shape

(12, 33)

In [53]:
df[df["adults"] > 10][["hotel", "adults", "children", "babies", "market_segment", 
      "distribution_channel", "agent", "company", "is_canceled"]]

,hotel,adults,children,babies,market_segment,distribution_channel,agent,company,is_canceled
1539,Resort Hotel,40,0.0,0,Direct,Direct,0,0,1
1587,Resort Hotel,26,0.0,0,Offline TA/TO,TA/TO,96,0,1
1643,Resort Hotel,50,0.0,0,Direct,Direct,0,0,1
1752,Resort Hotel,26,0.0,0,Offline TA/TO,TA/TO,96,0,1
1884,Resort Hotel,26,0.0,0,Offline TA/TO,TA/TO,96,0,1
1917,Resort Hotel,27,0.0,0,Direct,Direct,0,0,1
1962,Resort Hotel,27,0.0,0,Direct,Direct,0,0,1
2003,Resort Hotel,26,0.0,0,Offline TA/TO,TA/TO,96,0,1
2164,Resort Hotel,26,0.0,0,Offline TA/TO,TA/TO,96,0,1
2173,Resort Hotel,55,0.0,0,Direct,Direct,0,0,1
2228,Resort Hotel,20,0.0,0,Direct,Direct,0,0,1
2418,Resort Hotel,20,0.0,0,Direct,Direct,0,0,1

In [55]:
df["adults"].max()

55

In [57]:
df[df["adults"] > 10][["hotel", "adults", "children", "babies", "market_segment", 
      "distribution_channel", "agent", "company", "is_canceled"]].value_counts()

hotel         adults  children  babies  market_segment  distribution_channel  agent  company  is_canceled
Resort Hotel  26      0.0       0       Offline TA/TO   TA/TO                 96     0        1              5
              20      0.0       0       Direct          Direct                0      0        1              2
              27      0.0       0       Direct          Direct                0      0        1              2
              40      0.0       0       Direct          Direct                0      0        1              1
              50      0.0       0       Direct          Direct                0      0        1              1
              55      0.0       0       Direct          Direct                0      0        1              1
Name: count, dtype: int64

In [59]:
df[df["adults"] > 10][["adults", "stays_in_weekend_nights", "stays_in_week_nights", 
                                   "reserved_room_type", "assigned_room_type"]]

,adults,stays_in_weekend_nights,stays_in_week_nights,reserved_room_type,assigned_room_type
1539,40,0,3,A,A
1587,26,2,5,A,A
1643,50,1,2,A,A
1752,26,2,5,A,A
1884,26,2,5,A,A
1917,27,1,3,A,A
1962,27,1,3,A,A
2003,26,2,5,A,A
2164,26,2,5,A,A
2173,55,2,0,A,A
2228,20,2,5,D,D
2418,20,2,5,D,D

In [84]:
month_map = {
    "January": 1,
    "February": 2,
    "March": 3,
    "April": 4,
    "May": 5,
    "June": 6,
    "July": 7,
    "August": 8,
    "September": 9,
    "October": 10,
    "November": 11,
    "December": 12
}

In [85]:
df["arrival_month_num"] = df["arrival_date_month"].map(month_map)

In [86]:
df[df["arrival_month_num"].isna()][
    ["arrival_date_month", "arrival_month_num"]
].head()

Empty DataFrame
Columns: [arrival_date_month, arrival_month_num]
Index: []

In [87]:
df["arrival_month_num"].isna().sum()

np.int64(0)

In [89]:
df["arrival_date"] = pd.to_datetime(
    df["arrival_date_year"].astype(str) + "-" +
    df["arrival_month_num"].astype(str) + "-" +
    df["arrival_date_day_of_month"].astype(str)
)

In [90]:
df[["arrival_date_year", "arrival_date_month",
    "arrival_date_day_of_month", "arrival_date"]].head()

,arrival_date_year,arrival_date_month,arrival_date_day_of_month,arrival_date
0,2015,July,1,2015-07-01
1,2015,July,1,2015-07-01
2,2015,July,1,2015-07-01
3,2015,July,1,2015-07-01
4,2015,July,1,2015-07-01

In [ ]:
df = df.drop(columns=["arrival_date_year", "arrival_date_month",
    "arrival_date_day_of_month"])

In [95]:
df = df.drop(columns=["arrival_month_num"])

In [96]:
df["total_stay_nights"] = (
    df["stays_in_weekend_nights"] + df["stays_in_week_nights"]
)

In [98]:
import numpy as np

df["booking_status"] = np.where(
    df["is_canceled"] ==1, "Cancelled", "Not Cancelled"
)

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 87009 entries, 0 to 119389
Data columns (total 33 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           87009 non-null  object
 1   is_canceled                     87009 non-null  int64
 2   lead_time                       87009 non-null  int64
 3   arrival_date_week_number        87009 non-null  int64
 4   stays_in_weekend_nights         87009 non-null  int64
 5   stays_in_week_nights            87009 non-null  int64
 6   adults                          87009 non-null  int64
 7   children                        87009 non-null  float64
 8   babies                          87009 non-null  int64
 9   meal                            87009 non-null  object
 10  country                         87009 non-null  object
 11  market_segment                  87009 non-null  object
 12  distribution_channel            87009 non-null  object
 13  is_repeated_guest               87009 non-null  int64
 14  previous_cancellations          87009 non-null  int64
 15  previous_bookings_not_canceled  87009 non-null  int64
 16  reserved_room_type              87009 non-null  object
 17  assigned_room_type              87009 non-null  object
 18  booking_changes                 87009 non-null  int64
 19  deposit_type                    87009 non-null  object
 20  agent                           87009 non-null  int64
 21  company                         87009 non-null  int64
 22  days_in_waiting_list            87009 non-null  int64
 23  customer_type                   87009 non-null  object
 24  adr                             87009 non-null  float64
 25  required_car_parking_spaces     87009 non-null  int64
 26  total_of_special_requests       87009 non-null  int64
 27  reservation_status              87009 non-null  object
 28  reservation_status_date         87009 non-null  object
 29  childern                        87009 non-null  int64
 30  arrival_date                    87009 non-null  datetime64[ns]
 31  total_stay_nights               87009 non-null  int64
 32  booking_status                  87009 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(18), object(12)
memory usage: 22.6+ MB

In [100]:
df.describe()

,is_canceled,lead_time,arrival_date_week_number,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,...,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,childern,arrival_date,total_stay_nights
count,87009.000000,87009.000000,87009.000000,87009.00000,87009.000000,87009.000000,87009.000000,87009.000000,87009.000000,87009.000000,...,87009.000000,87009.000000,87009.000000,87009.000000,87009.000000,87009.000000,87009.000000,87009.000000,87009,87009.000000
mean,0.274995,79.861566,26.835385,1.00462,2.623993,1.884092,0.134136,0.010838,0.038640,0.030457,...,0.268225,81.269305,11.011815,0.748187,106.522910,0.084497,0.698135,0.134136,2016-09-15 00:30:41.023342336,3.628613
min,0.000000,0.000000,1.000000,0.00000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2015-07-01 00:00:00,0.000000
25%,0.000000,11.000000,16.000000,0.00000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,9.000000,0.000000,0.000000,72.250000,0.000000,0.000000,0.000000,2016-04-01 00:00:00,2.000000
50%,0.000000,49.000000,27.000000,1.00000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,9.000000,0.000000,0.000000,98.330000,0.000000,0.000000,0.000000,2016-09-20 00:00:00,3.000000
75%,1.000000,125.000000,37.000000,2.00000,4.000000,2.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,240.000000,0.000000,0.000000,134.100000,0.000000,1.000000,0.000000,2017-04-01 00:00:00,5.000000
max,1.000000,737.000000,53.000000,19.00000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,...,18.000000,535.000000,543.000000,391.000000,510.000000,8.000000,5.000000,10.000000,2017-08-31 00:00:00,69.000000
std,0.446514,86.007673,13.666032,1.02765,2.040980,0.615313,0.446647,0.113698,0.192736,0.369781,...,0.710287,110.054712,54.022085,10.013623,51.898983,0.281950,0.831706,0.446647,NaN,2.744639

In [102]:
df.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_week_number          0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
company                           0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
childern                          0
arrival_date                      0
total_stay_nights                 0
booking_status                    0
dtype: int64

In [103]:
df.to_csv("D:\DA - projects\END-TO-END\Hotel-Booking-Demand\data\hotel_bookings_cleaned.csv", index = False)